
import React from 'react';
import { AlertTriangle } from 'lucide-react';

const Disclaimer: React.FC = () => {
  return (
    <section id="disclaimer" className="relative py-24 px-6 bg-cyber-bg-dark">
      <div className="max-w-4xl mx-auto">
        {/* Section header */}
        <div className="text-center mb-10">
          <div className="inline-block mb-4 cyber-card px-3 py-1 border-cyber-neon-blue/30">
            <p className="text-cyber-neon-blue text-sm tracking-wider flex items-center gap-2">
              <AlertTriangle className="w-4 h-4" />
              <span>LEGAL INFORMATION</span>
            </p>
          </div>
          <h2 className="text-3xl md:text-4xl font-bold mb-6">
            Legal <span className="text-gradient">Disclaimer</span>
          </h2>
        </div>
        
        {/* Disclaimer content */}
        <div className="cyber-card text-cyber-text-secondary">
          <div className="space-y-6">
            <p>
              Podcast Script Writer GPT is an AI-powered tool designed to assist with creating podcast scripts. 
              The following disclaimer outlines the terms of use and limitations of our service:
            </p>
            
            <div>
              <h3 className="text-white font-semibold mb-2">Content Ownership & Copyright</h3>
              <p>
                Scripts generated through Podcast Script Writer GPT are owned by you. However, you are responsible 
                for ensuring that any content you create does not infringe upon existing copyrights, trademarks, 
                or intellectual property rights of others. AI Web Tools LLC does not claim ownership of the content 
                generated through this tool.
              </p>
            </div>
            
            <div>
              <h3 className="text-white font-semibold mb-2">Accuracy & Quality</h3>
              <p>
                While we strive to provide high-quality script generation, the tool may occasionally produce 
                content that contains inaccuracies, inconsistencies, or errors. Users should thoroughly review 
                all generated content before publication or distribution. AI Web Tools LLC is not responsible 
                for verifying the accuracy of information in your scripts.
              </p>
            </div>
            
            <div>
              <h3 className="text-white font-semibold mb-2">Limitation of Liability</h3>
              <p>
                Podcast Script Writer GPT is provided "as is" without warranties of any kind, either express 
                or implied. In no event shall AI Web Tools LLC, its affiliates, or its partners be liable for 
                any direct, indirect, incidental, special, or consequential damages arising from the use of 
                this tool or any content generated by it.
              </p>
            </div>
            
            <div>
              <h3 className="text-white font-semibold mb-2">Acceptable Use</h3>
              <p>
                You agree not to use Podcast Script Writer GPT to create content that is unlawful, harmful, 
                threatening, abusive, harassing, defamatory, vulgar, obscene, invasive of another's privacy, 
                hateful, or racially, ethnically, or otherwise objectionable. The tool should not be used to 
                generate content that promotes illegal activities or violates any applicable laws.
              </p>
            </div>
            
            <div>
              <h3 className="text-white font-semibold mb-2">Service Availability</h3>
              <p>
                We aim to provide uninterrupted access to Podcast Script Writer GPT, but we do not guarantee 
                that the service will be available at all times. We reserve the right to modify, suspend, or 
                discontinue the service at any time without notice.
              </p>
            </div>
            
            <div>
              <h3 className="text-white font-semibold mb-2">Third-Party Services</h3>
              <p>
                Podcast Script Writer GPT is built upon OpenAI's technology. By using our tool, you are also 
                subject to OpenAI's terms of service and privacy policy.
              </p>
            </div>
            
            <p>
              By using Podcast Script Writer GPT, you acknowledge that you have read, understood, and agree 
              to the terms outlined in this disclaimer. AI Web Tools LLC reserves the right to update or modify 
              this disclaimer at any time without prior notice.
            </p>
            
            <p className="text-sm">
              Last updated: May 2025
            </p>
          </div>
        </div>
        
        {/* Privacy and Terms links */}
        <div className="mt-10 text-center">
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <a 
              href="https://openai.com/policies/privacy-policy/" 
              target="_blank" 
              rel="noopener noreferrer"
              className="neon-button"
            >
              Privacy Policy
            </a>
            <a 
              href="https://aiwebtools.ai/terms-of-services" 
              target="_blank" 
              rel="noopener noreferrer"
              className="neon-button"
            >
              Terms of Service
            </a>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Disclaimer;
